### ISSUE TITLE
Morpheus Upgrade using Hombrew Fails at the Ninja package install on Mac Studio M1 Max OS 13.6.4, Xcode 15.2

### ISSUE THREAD

**Issue by rouscat** [morpheus-lab/homebrew-morpheus#22]
This is a problem when trying to upgrade or newly install on Mac Studios with M1 Max running OS 13.6.4.  

There was no problem upgrading on an Intel i7 iMac running OS 12.7.3.

![Screenshot 2024-02-08 at 09 52 27](https://github.com/morpheus-lab/homebrew-morpheus/assets/159491866/f9a1fdd6-f4b3-4f41-ab5d-df83146c6e46)

**Comment by jdieg0** [comment]
Hi @rouscat,

we're currently experiencing problems with some macOS SDKs failing to build libSBML. Meanwhile, Morpheus 2.3.6, which was just released a few moments ago (announcement to follow soon), has the SBML import disabled by default.

So a `brew update` and a `brew upgrade` (which defaults to the no SBML option) should now work on your M1 Mac Studio with macOS 13 again. If you need SBML support, you can still add this option on machines without this macOS SDK issue, e.g. on your Intel Mac with macOS 12 as follows: `brew install morpheus --with-sbml`.

Best,
Diego

**Comment by rouscat** [comment]
That fixed it.  Thanks.
